apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaproducer-deployment
  labels:
    app: kafkaproducer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafkaproducer
  template:
    metadata:
      labels:
        app: kafkaproducer
    spec:
      containers:
      - name: confluent-client
        image: confluentinc/cp-kafka:5.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        command:
          - sh
          - -c
          - "kafka-producer-perf-test --topic kafkavpntest --num-records 10 --record-size 10 --throughput 1 --producer-props bootstrap.servers=kafka-0-broker.kafka.autoip.dcos.thisdcos.directory:1026,kafka-1-broker.kafka.autoip.dcos.thisdcos.directory:1025,kafka-2-broker.kafka.autoip.dcos.thisdcos.directory:1025 && sleep 60"
      restartPolicy: Always
